version: 2
updates:
- package-ecosystem: pip
  directory: "/requirements"
  schedule:
    interval: daily
    time: "22:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: pylint
    versions:
    - 2.6.1
    - 2.6.2
    - 2.7.0
    - 2.7.1
    - 2.7.2
    - 2.7.3
    - 2.7.4
    - 2.8.0
    - 2.8.1
  - dependency-name: twitterapi
    versions:
    - 2.6.10
    - 2.6.4.1
    - 2.6.5
    - 2.6.6
    - 2.6.7
    - 2.6.8
    - 2.6.9
    - 2.6.9.1
    - 2.7.0
    - 2.7.1
    - 2.7.2
  - dependency-name: pytest-asyncio
    versions:
    - 0.15.0
  - dependency-name: importlib-metadata
    versions:
    - 3.10.0
    - 3.10.1
    - 3.4.0
    - 3.5.0
    - 3.6.0
    - 3.7.0
    - 3.7.2
    - 3.7.3
    - 3.8.0
    - 3.8.1
    - 3.9.0
    - 3.9.1
    - 4.0.0
  - dependency-name: pillow
    versions:
    - 8.1.0
    - 8.1.1
    - 8.1.2
  - dependency-name: tqdm
    versions:
    - 4.56.0
    - 4.56.1
    - 4.56.2
    - 4.57.0
    - 4.58.0
    - 4.59.0
  - dependency-name: inflect
    versions:
    - 5.0.2
    - 5.0.3
    - 5.2.0
  - dependency-name: python-magic
    versions:
    - 0.4.20
    - 0.4.21
  - dependency-name: soupsieve
    versions:
    - "2.1"
    - "2.2"
  - dependency-name: pytest
    versions:
    - 6.2.2
  - dependency-name: isort
    versions:
    - 5.7.0
  - dependency-name: typed-ast
    versions:
    - 1.4.2
  - dependency-name: packaging
    versions:
    - "20.8"
  - dependency-name: lxml
    versions:
    - 4.6.2
  - dependency-name: aiohttp
    versions:
    - 3.7.3
