//
// This file is autogenerated.
// To update, run:
//
//    make Jenkinsfile
//

pipeline {
    agent none
    environment {
        GIT_COMMITTER_NAME  = 'Joe Doe'
        GIT_COMMITTER_EMAIL = 'joe.doe@example.com'
        HOME                = '/tmp/'
    }
    options {
        timestamps()
    }
    stages {
        stage('Parallel Stage') {
            parallel {
                stage('Python:3.5.3') {
                    agent {
                        docker {
                            image 'python:3.5.3'
                        }
                    }
                    stages {
                        stage('Checkout') {
                            steps {
                                checkout scm
                            }
                        }
                        stage('Install') {
                            steps {
                                sh 'make install'
                            }
                        }
                        stage('Test') {
                            steps {
                                sh 'make test'
                            }
                        }
                    }
                }
                stage('Python:3.5.4') {
                    agent {
                        docker {
                            image 'python:3.5.4'
                        }
                    }
                    stages {
                        stage('Checkout') {
                            steps {
                                checkout scm
                            }
                        }
                        stage('Install') {
                            steps {
                                sh 'make install'
                            }
                        }
                        stage('Test') {
                            steps {
                                sh 'make test'
                            }
                        }
                    }
                }
                stage('Python:3.5.5') {
                    agent {
                        docker {
                            image 'python:3.5.5'
                        }
                    }
                    stages {
                        stage('Checkout') {
                            steps {
                                checkout scm
                            }
                        }
                        stage('Install') {
                            steps {
                                sh 'make install'
                            }
                        }
                        stage('Test') {
                            steps {
                                sh 'make test'
                            }
                        }
                    }
                }
                stage('Python:3.6.0') {
                    agent {
                        docker {
                            image 'python:3.6.0'
                        }
                    }
                    stages {
                        stage('Checkout') {
                            steps {
                                checkout scm
                            }
                        }
                        stage('Install') {
                            steps {
                                sh 'make install'
                            }
                        }
                        stage('Test') {
                            steps {
                                sh 'make test'
                            }
                        }
                    }
                }
                stage('Python:3.6.1') {
                    agent {
                        docker {
                            image 'python:3.6.1'
                        }
                    }
                    stages {
                        stage('Checkout') {
                            steps {
                                checkout scm
                            }
                        }
                        stage('Install') {
                            steps {
                                sh 'make install'
                            }
                        }
                        stage('Test') {
                            steps {
                                sh 'make test'
                            }
                        }
                    }
                }
                stage('Python:3.6.2') {
                    agent {
                        docker {
                            image 'python:3.6.2'
                        }
                    }
                    stages {
                        stage('Checkout') {
                            steps {
                                checkout scm
                            }
                        }
                        stage('Install') {
                            steps {
                                sh 'make install'
                            }
                        }
                        stage('Test') {
                            steps {
                                sh 'make test'
                            }
                        }
                    }
                }
                stage('Python:3.6.3') {
                    agent {
                        docker {
                            image 'python:3.6.3'
                        }
                    }
                    stages {
                        stage('Checkout') {
                            steps {
                                checkout scm
                            }
                        }
                        stage('Install') {
                            steps {
                                sh 'make install'
                            }
                        }
                        stage('Test') {
                            steps {
                                sh 'make test'
                            }
                        }
                    }
                }
                stage('Python:3.6.4') {
                    agent {
                        docker {
                            image 'python:3.6.4'
                        }
                    }
                    stages {
                        stage('Checkout') {
                            steps {
                                checkout scm
                            }
                        }
                        stage('Install') {
                            steps {
                                sh 'make install'
                            }
                        }
                        stage('Test') {
                            steps {
                                sh 'make test'
                            }
                        }
                    }
                }
                stage('Python:3.6.5') {
                    agent {
                        docker {
                            image 'python:3.6.5'
                        }
                    }
                    stages {
                        stage('Checkout') {
                            steps {
                                checkout scm
                            }
                        }
                        stage('Install') {
                            steps {
                                sh 'make install'
                            }
                        }
                        stage('Test') {
                            steps {
                                sh 'make test'
                            }
                        }
                    }
                }
            }
        }
    }
}
