//
// This file is autogenerated.
// To update, run:
//
//    make Jenkinsfile
//

pipeline {
    agent none
    environment {
        GIT_COMMITTER_NAME  = 'Joe Doe'
        GIT_COMMITTER_EMAIL = 'joe.doe@example.com'
        HOME                = '/tmp/'
    }
    options {
        timestamps()
    }
    stages {
        stage('Parallel Stage') {
            parallel {
                stage('Python:3.5.3') {
                    agent {
                        docker {
                            image 'python:3.5.3'
                        }
                    }
                    stages {
                        stage('Python:3.5.3 Checkout') {
                            steps {
                                checkout scm
                            }
                        }
                        stage('Python:3.5.3 Install') {
                            steps {
                                sh 'make install'
                            }
                        }
                        stage('Python:3.5.3 Test') {
                            steps {
                                sh 'make test'
                            }
                        }
                    }
                }
                stage('Python:3.5.4') {
                    agent {
                        docker {
                            image 'python:3.5.4'
                        }
                    }
                    stages {
                        stage('Python:3.5.4 Checkout') {
                            steps {
                                checkout scm
                            }
                        }
                        stage('Python:3.5.4 Install') {
                            steps {
                                sh 'make install'
                            }
                        }
                        stage('Python:3.5.4 Test') {
                            steps {
                                sh 'make test'
                            }
                        }
                    }
                }
                stage('Python:3.5.5') {
                    agent {
                        docker {
                            image 'python:3.5.5'
                        }
                    }
                    stages {
                        stage('Python:3.5.5 Checkout') {
                            steps {
                                checkout scm
                            }
                        }
                        stage('Python:3.5.5 Install') {
                            steps {
                                sh 'make install'
                            }
                        }
                        stage('Python:3.5.5 Test') {
                            steps {
                                sh 'make test'
                            }
                        }
                    }
                }
                stage('Python:3.5.6') {
                    agent {
                        docker {
                            image 'python:3.5.6'
                        }
                    }
                    stages {
                        stage('Python:3.5.6 Checkout') {
                            steps {
                                checkout scm
                            }
                        }
                        stage('Python:3.5.6 Install') {
                            steps {
                                sh 'make install'
                            }
                        }
                        stage('Python:3.5.6 Test') {
                            steps {
                                sh 'make test'
                            }
                        }
                    }
                }
                stage('Python:3.6.0') {
                    agent {
                        docker {
                            image 'python:3.6.0'
                        }
                    }
                    stages {
                        stage('Python:3.6.0 Checkout') {
                            steps {
                                checkout scm
                            }
                        }
                        stage('Python:3.6.0 Install') {
                            steps {
                                sh 'make install'
                            }
                        }
                        stage('Python:3.6.0 Test') {
                            steps {
                                sh 'make test'
                            }
                        }
                    }
                }
                stage('Python:3.6.1') {
                    agent {
                        docker {
                            image 'python:3.6.1'
                        }
                    }
                    stages {
                        stage('Python:3.6.1 Checkout') {
                            steps {
                                checkout scm
                            }
                        }
                        stage('Python:3.6.1 Install') {
                            steps {
                                sh 'make install'
                            }
                        }
                        stage('Python:3.6.1 Test') {
                            steps {
                                sh 'make test'
                            }
                        }
                    }
                }
                stage('Python:3.6.2') {
                    agent {
                        docker {
                            image 'python:3.6.2'
                        }
                    }
                    stages {
                        stage('Python:3.6.2 Checkout') {
                            steps {
                                checkout scm
                            }
                        }
                        stage('Python:3.6.2 Install') {
                            steps {
                                sh 'make install'
                            }
                        }
                        stage('Python:3.6.2 Test') {
                            steps {
                                sh 'make test'
                            }
                        }
                    }
                }
                stage('Python:3.6.3') {
                    agent {
                        docker {
                            image 'python:3.6.3'
                        }
                    }
                    stages {
                        stage('Python:3.6.3 Checkout') {
                            steps {
                                checkout scm
                            }
                        }
                        stage('Python:3.6.3 Install') {
                            steps {
                                sh 'make install'
                            }
                        }
                        stage('Python:3.6.3 Test') {
                            steps {
                                sh 'make test'
                            }
                        }
                    }
                }
                stage('Python:3.6.4') {
                    agent {
                        docker {
                            image 'python:3.6.4'
                        }
                    }
                    stages {
                        stage('Python:3.6.4 Checkout') {
                            steps {
                                checkout scm
                            }
                        }
                        stage('Python:3.6.4 Install') {
                            steps {
                                sh 'make install'
                            }
                        }
                        stage('Python:3.6.4 Test') {
                            steps {
                                sh 'make test'
                            }
                        }
                    }
                }
                stage('Python:3.6.5') {
                    agent {
                        docker {
                            image 'python:3.6.5'
                        }
                    }
                    stages {
                        stage('Python:3.6.5 Checkout') {
                            steps {
                                checkout scm
                            }
                        }
                        stage('Python:3.6.5 Install') {
                            steps {
                                sh 'make install'
                            }
                        }
                        stage('Python:3.6.5 Test') {
                            steps {
                                sh 'make test'
                            }
                        }
                    }
                }
                stage('Python:3.6.6') {
                    agent {
                        docker {
                            image 'python:3.6.6'
                        }
                    }
                    stages {
                        stage('Python:3.6.6 Checkout') {
                            steps {
                                checkout scm
                            }
                        }
                        stage('Python:3.6.6 Install') {
                            steps {
                                sh 'make install'
                            }
                        }
                        stage('Python:3.6.6 Test') {
                            steps {
                                sh 'make test'
                            }
                        }
                    }
                }
                stage('Python:3.6.7') {
                    agent {
                        docker {
                            image 'python:3.6.7'
                        }
                    }
                    stages {
                        stage('Python:3.6.7 Checkout') {
                            steps {
                                checkout scm
                            }
                        }
                        stage('Python:3.6.7 Install') {
                            steps {
                                sh 'make install'
                            }
                        }
                        stage('Python:3.6.7 Test') {
                            steps {
                                sh 'make test'
                            }
                        }
                    }
                }
                stage('Python:3.7.0') {
                    agent {
                        docker {
                            image 'python:3.7.0'
                        }
                    }
                    stages {
                        stage('Python:3.7.0 Checkout') {
                            steps {
                                checkout scm
                            }
                        }
                        stage('Python:3.7.0 Install') {
                            steps {
                                sh 'make install'
                            }
                        }
                        stage('Python:3.7.0 Test') {
                            steps {
                                sh 'make test'
                            }
                        }
                    }
                }
            }
        }
    }
}
