#!/usr/bin/env bash

TARGET="`dirname $0`/../requirements-dev.in"

set -x

cat <<EOF > ${TARGET}
#
# This file is autogenerated
# To update, run:
#
#    make requirements-dev.in
#
-r requirements.in
`find tests/ -name requirements.in -printf '%h %d %p\n' \
    | sort -n \
    | awk '{ print "-r " $3 }'`
EOF
