#!/usr/bin/env bash

TARGET="`dirname $0`/../requirements.in"

set -x

cat <<EOF > ${TARGET}
#
# This file is autogenerated
# To update, run:
#
#    make requirements.in
#
`find hangupsbot/ -name requirements.in -printf '%h %d %p\n' \
    | sort -n \
    | awk '{ print "-r " $3 }'`
EOF
